version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - pg
    ports:
      - 4000:4000
    stdin_open: true
    tty: true

  pg:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
